import './button.scss'
import './_white-text/button_white-text.scss'
import './_purple-text/button_purple-text.scss'
import './_pay/button_pay.scss'
import './_link/button_link.scss'
import './_like/button_like'