import './switch.scss'
import './_toggle/switch_toggle.scss'
import './_radio/switch_radio.scss'
import './_radio_white/switch_radio_white.scss'
import './_checkbox/switch_checkbox.scss'
import './_checkbox/_rich/switch_checkbox_rich.scss'